# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20180110_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='urgentcare_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
